# Generated by Django 3.2.5 on 2021-11-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
