# Generated by Django 3.2.5 on 2021-11-01 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0002_alter_images_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='k',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imageuploader.post'),
        ),
    ]
